version: "3.8"
services:
  test-odoo:
    container_name: web-odoo
    image: odoo:latest
    depends_on:
      - postgresdb
    ports:
      - 8069:8069
    environment:
      - HOST=postgresdb
      - USER=root
      - PASSWORD=root
    networks:
      - odoo-network
    volumes:
      - odoo_app:/var/lib/odoo
      - odoo_app:/etc/odoo
      - odoo_app:/mnt/extra-addons
  postgresdb:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - odoo-network
    volumes:
      - odoo_db:/var/lib/postgresql/data/pgdata

networks:
  odoo-network:
    driver: bridge
volumes:
  odoo_app:
    driver: local
    driver_opts:
      type: none
      device: /data/app
      o: bind
  odoo_db:
    driver: local
    driver_opts:
      type: none
      device: /data/db
      o: bind
